### PR TITLE
Small corrections

### PR DESCRIPTION
**Pull request by BTowersCoding**

### CODE REVIEW

**Review by glennj — APPROVED** [review]

**Comment by glennj** [comment]
A draft PR: I approved too soon

**Comment by glennj** [comment]
BTW, thanks for looking at this @BTowersCoding

**Comment by BTowersCoding** [comment]
Yeah I've only begun to scratch the surface because I've had so much going on lately, but this is loads of fun and I definitely intend to contribute more... thanks for putting this together!

**Comment by IsaacG** [comment]
Given that this PR is currently showing a two word diff and hasn't been touched in a while, I'll just close out this PR. Please feel free to reopen once you want to continue with this change!

**Pull request closed without merging**
