### PR TITLE
updated links to jqlang.github.io

### PR DESCRIPTION
**Pull request by senarclens**
this preserves the anchors to the correct headings which are lost in the gh redirects before the change

## Summary

(Explain what this change is attempting to accomplish)

## Checklist
- [ ] If docs where changed, run `./bin/configlet generate` to ensure all documents are properly generated.
- [ ] CI is green

### CODE REVIEW

**Comment by glennj** [comment]
`stedolan.github.io` appears all over the repo. Do you want to expand the scope of your PR to fix them all?

**Comment by senarclens** [comment]
@glennj : done
(via
```shell
find . \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/github\.com\/stedolan/github\.com\/jqlang/g'
```
and
```shell
find . \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/stedolan\.github\.io/jqlang\.github\.io/g'
```

Also fixed a few capitalization issues in the `#` fragments along the way discovered when testing the new links.

**Review by IsaacG — APPROVED** [review]

**Comment by glennj** [comment]
@senarclens Referencing https://forum.exercism.org/t/what-sets-the-average-run-time/6680, can you please change [line 19](https://github.com/exercism/jq/blob/5910d26cac9495313cc83b2fa6bbd39a7d1530fc/config.json#L19) in `config.json` to satisfy the configlet check.

**Comment by glennj** [comment]
@senarclens thanks for taking care of this!

**Pull request merged**
